apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cdt
    image: quay.io/eclipse-cdt/cdt-infra-plus-eclipse-install@sha256:87cf4b58119836c1a784a049b3eaafe79ab1acd4c88455cd2cd41e5e31f0b900
    tty: true
    args: ["/bin/sh", "-c", "/home/vnc/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "10000Mi"
        cpu: "1"
      limits:
        memory: "10000Mi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
    - name: volume-known-hosts
      mountPath: /home/jenkins/.ssh
    - name: "jenkins-home"
      mountPath: "/home/jenkins"
      readOnly: false
    - name: tools
      mountPath: /jipp/tools
  - name: jnlp
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
    - name: volume-known-hosts
      mountPath: /home/jenkins/.ssh
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
  - name: volume-known-hosts
    configMap:
      name: known-hosts
  - name: "jenkins-home"
    emptyDir: {}
  - name: tools
    persistentVolumeClaim:
      claimName: tools-claim-jiro-cdt
